### PR TITLE
Fix coroutines lock

### PR DESCRIPTION
**Pull request by dennypenta**
https://github.com/ReactiveX/RxGo/issues/172

### CODE REVIEW

**Comment by teivah** [comment]
Hey @dennypenta, thanks for the PR but I do not want to add new features to the v1 (only fixes, if any). 
Meanwhile, any PR related the `v2` branch is more than welcome.

**Comment by teivah** [comment]
Thanks @dennypenta for the proposition. I did not see at first sight that the PR was related to a v1 bug.
Anyway, it seems your PR leads to a testing issue: https://travis-ci.org/ReactiveX/RxGo/jobs/504931849

Please make sure to pass all the RxGo tests.

**Comment by dennypenta** [comment]
Do you mean that it's gonne be fixed in v2, don't you?

**Comment by teivah** [comment]
> Do you mean that it's gonna be fixed in v2, don't you?

It is not handled in the v2 yet. However, if we apply a fix in the v1 it will be propagated in the v2.

What I said, though, is that your PR **does not pass the unit tests**. So before to consider your PR, please fix that.

Also, please consider changing the PR and issue name. "Fix coroutines lock" is kind of vague. If I understand your point, it's rather a potential leak problem related to the `Start` operator so _Fixing potential channel leak on Start operator_ would be more appropriate in my humble opinion.

Thank you.

**Comment by teivah** [comment]
@dennypenta I'm cleaning the backlog and I'm closing this PR. If you want to work on it, later on, feel free to do it (and to make sure you pass the test 😉).

**Pull request closed without merging**
