### PR TITLE
Fix: https://github.com/ReactiveX/RxGo/issues/234

### PR DESCRIPTION
**Pull request by v-zubko**
Maybe Window function also should be addressed?

### CODE REVIEW

**Comment by v-zubko** [comment]
Yup, I saw :) @teivah  Does this change do in a right way? Or you would do it different? Do I have to update `BufferWithTimeOrCount`, `WindowWithTime` and `WindowWithTimeOrCount`?

**Comment by teivah** [comment]
> Yup, I saw :) @teivah Does this change go in a right way? Or you would do it different? Do I have to update `BufferWithTimeOrCount`, `WindowWithTime` and `WindowWithTimeOrCount`?

Yes, I like the approach. Let's forget about this `causalityDuration` for the time being and keep things simple.
If you want to tackle the others as well, yes please :)

**Comment by teivah** [comment]
@v-zubko Some tests are failing like `Test_Observable_WindowWithTime`

**Comment by v-zubko** [comment]
Where are they failing? CI is green :)

**Comment by teivah** [comment]
On my local env:
```
        	Error Trace:	assert.go:225
        	            				observable_operator_test.go:1665
        	Error:      	Not equal: 
        	            	expected: []interface {}{5, 6, 7}
        	            	actual  : []interface {}{5, 6, 7, 8}
```

Try repeating them. Also, some tests like `Test_Observable_BufferWithTime` are taking 9 seconds.

**Comment by v-zubko** [comment]
9 seconds is expected. Cause of delays.

**Comment by v-zubko** [comment]
BTW are you sure that you've got latest version? Cause I see another expected values:
```
Assert(ctx, t, JustItem((<-observe).V), HasItems(1, 2))
Assert(ctx, t, JustItem((<-observe).V), HasItems(3, 4, 5))
Assert(ctx, t, JustItem((<-observe).V), HasItems(6, 7, 8))
```

**Comment by teivah** [comment]
> BTW are you sure that you've got latest version? Cause I see another expected values:
> 
> ```
> Assert(ctx, t, JustItem((<-observe).V), HasItems(1, 2))
> Assert(ctx, t, JustItem((<-observe).V), HasItems(3, 4, 5))
> Assert(ctx, t, JustItem((<-observe).V), HasItems(6, 7, 8))
> ```

Nope, check at the files changed on this PR.

It's still:
```
Assert(ctx, t, (<-observe).V.(Observable), HasItems(0, 1))
Assert(ctx, t, (<-observe).V.(Observable), HasItems(2, 3, 4))
Assert(ctx, t, (<-observe).V.(Observable), HasItems(5, 6, 7))
```

Moreover, we can't keep a unit test to executes in 9 seconds.

**Comment by teivah** [comment]
No longer active

**Pull request closed without merging**
