### PR TITLE
Major refactoring & new operators

### PR DESCRIPTION
**Pull request by teivah**
Hey,

I know recently I've created a bunch of PR, some of them were going to different directions.
This is an aggregated PR containing both refactoring and new operators.

The major changes:
* Migration of `Connectable`, `Observer` and `Observable` into interfaces
* Creation of a new `Optional` interface to handle optional elements (e.g. `Reduce`)
* Creation of a new `Single` interface to handle single elements (e.g. `Count`)
* Creation of a new `ConnectableObservable` type (created with `Observable.Publish()`)
* Migration of the `fx` functions to not be tied anymore to a single operator (see https://github.com/ReactiveX/RxGo/issues/85)
* New `Error` operator
* New `Reduce` operator
* New `Count` operator
* New  `FirstOrDefault` and `LastOrDefault` operators
* New `TakeWhile` operator
* New `ToList` operator
* New `ToMap` and `ToMapWithValueSelector` operators
* New `Zip` operator
* New `Defer` operator
* New `ForEach` operator
* New `ElementAt` operator
* New `WithBufferedChannel` option

The testing debt should be fine as every new operator gets its unit test. Yet, there is probably a documentation debt with my current branch. Before to document every single change, I wanted to make sure this PR is going in the direction you wished.

I'm going to close my other PRs.

### CODE REVIEW

**Comment by avelino** [comment]
I liked work
We have a problem 😄, breaks the current API, for this reason I will generate a new version 2 and keeping the current as version 1, so we do not break the projects that uses RxGo.

**Comment by teivah** [comment]
Thanks @avelino. Yes, you're right it does break it.

Yet, if I understand correctly that was more or less one of the goal of https://github.com/ReactiveX/RxGo/projects/1#card-6433015.

But I like the idea to abstract those types into interfaces. For example, if one day we want to use something else than channel (like https://github.com/smartystreets/go-disruptor), this would be possible. Or we could also let the user implements its own factory.

**Comment by avelino** [comment]
Very very good news
Root level package let’s go
:D

**Comment by teivah** [comment]
@avelino Alright ^^ I'll just change the root package name to `rxgo`, as you requested.

**Pull request merged**
