### PR TITLE
Version 3

### LINKED ISSUE #250: Support dev.go2go branch with generics
Experimental go2go translator is published!
https://blog.golang.org/generics-next-step

### LINKED ISSUE #277: How to stop a Interval observable?
I'm missing a close, unsubscribe, dispose, etc. function? How am I supposed to stop it?

### LINKED ISSUE #281: SwitchMap available ?
Hi,

I have been using RxJS for quite a while and I found myself using SwitchMap when I want to produce a new observable in the stream and complete the previous.

What is the alternative in RxGo?

I can't find that operator in the documentation

Does anybody know what I should be using in this case?

Thanks in advance

### LINKED ISSUE #343: when to support the generic type
the golang support the generic type from 18 , when the rxgo to support it

### LINKED ISSUE #347: Why I can not find "Throttle" operator?

### LINKED ISSUE #362: SwitchMap operator
Hello! One of the best RX operators is SwitchMap, it looks like FlatMap, but this operator stops previous observable 
https://rxjs.dev/api/operators/switchMap

It is imperative to be able to complete the previous observable
**docs:**
Returns an Observable that emits items based on applying a function that you supply to each item emitted by the source Observable, where that function returns an (so-called "inner") Observable. Each time it observes one of these inner Observables, the output Observable begins emitting the items emitted by that inner Observable. When a new inner Observable is emitted, [switchMap](https://rxjs.dev/api/index/function/switchMap) stops emitting items from the earlier-emitted inner Observable and begins emitting items from the new one. It continues to behave like this for subsequent inner Observables.

Or maybe you can provide some advice? 
Example case:
```
func main() {
	observable := rxgo.Just(1, 2, 3)().FlatMap(func(i rxgo.Item) rxgo.Observable {
		println("new item", i.V.(int))
		return rxgo.Interval(rxgo.WithDuration(time.Second * 1))
	})
	for el := range observable.Observe() {
		println(el.V.(int))
	}
}
```
I want to make a new observable each time after Just or other Observable creators emit a new value. In this case nice to unsubscribe from interval and create new observable 

_P.S Well, as I can see the flat map operator doesn't work too_
output
```
new item 1
0
1
2
3
4
5
6
```

### LINKED ISSUE #375: Go 1.18 Generics Support
Since Go came out with generics on version 1.18,  the need for interface{} in type parameters is no longer needed. I understand the need for backwards compatability, however I do feel that this library would very much benefit from generics especially when making operations less error prone and code more concise.

I do propose making a separate variation of the library to support genetics so the current implementation remains backwards compatible.

### PR DESCRIPTION
**Pull request by si3nloong**
This is a draft PR for the upcoming release version `v3`, it will break and redesign the whole reactive API using the generics feature offered by **Go 1.18**. Technically, this PR will resolve issues #375 #250 #343, as well as some missing features such as #362 #347.

⚠️⚠️⚠️ This is still under heavy development, PR is just to keep track of the overall progression.

> I'm trying to map the [rxjs](https://rxjs.dev/) API design to this lib as much as possible

**Alpha Version**
CHANGELOG :
- [x] remove `vendor` packages and use `go.mod` instead
- [x] utilize generic to implement strong type
- [x] rework **Observe** API to let user to be able to control the subscription
- [x] set minimum go version to **v1.19** (required **Generics** and **sync.Pointer**)
- [ ] add test cases for every function
- [ ] update `README` and API documentation

**Beta Version**
CHANGELOG :
- [ ] add Hot observable such as `BehaviorSubject`
- [ ] refactor to [scheduler](https://rxjs.dev/guide/scheduler), references: 
   - https://medium.com/swlh/understanding-rxphp-schedulers-part-1-d3c0ab6eb881
   - https://medium.com/@jakob.mats/understanding-rxphp-schedulers-part-2-6c4d01d7e65e

Request for comments : 
- API look and feel

### CODE REVIEW

**Comment by si3nloong** [comment]
Proposal for new structure : 

Current : 
```go
for v := range observable.Observe() {}

// OR 
obs := observable.Observe()
for {
   select {
   case item, ok :=<- obs:
   }
}
```

Proposed : 
```go
type Subscription interface {
   Unsubscribe()
}

observable[T].Subscribe(onNext func(T), onError func(error), onCompleted func()) Subscription
```

**Comment by si3nloong** [comment]
The new version of API will look like this. @teivah any comments?
Screenshot 2022-08-30 at 11 08 40 AM

**Comment by si3nloong** [comment]
There are significant changes in the API. For example,

**Previous**
```go
rxgo.Defer([]Producer{func(ctx context.Context, next chan<- Item) {
	next <- Of(1)
	next <- Of(2)
	next <- Error(fmt.Errorf("some error"))
}})
```

**Current** 
```go
rxgo.Defer(func() rxgo.IObservable[uint] {
   return rxgo.Interval(1000)
})
```

**Comment by pmbanka** [comment]
I took a look at this PR (massive work!), and I got curious about one thing - do you plan on porting the [scheduler](https://rxjs.dev/guide/scheduler) concept to rxgo as well? I would mainly find it useful to be able to mock/control time in my tests.

**Comment by si3nloong** [comment]
> I took a look at this PR (massive work!), and I got curious about one thing - do you plan on porting the [scheduler](https://rxjs.dev/guide/scheduler) concept to rxgo as well? I would mainly find it useful to be able to mock/control time in my tests.

I will take a look on that after finish the general API, I think should be feasible.

**Comment by si3nloong** [comment]
I'm IDLE for some time due to work, will continue on this, so far the basic functionality is OK to go atm.

**Comment by adhaamehab** [comment]
@si3nloong hello, is this PR still active? I would love to pick it up to get a feel if about maintaining this package, but don't want to over step if you have timed plan to complete it.

**Review by davidlondono — APPROVED** [review]

**Comment by Olshansk** [comment]
@davidlondono @si3nloong Wanted to bump the thread to see if this PR will ever get picked up again.

**Comment by plastikfan** [comment]
I'm interested to know if this pull request is still  thing as I am in the process of defining my own V3 which uses generics, not sure about the other issues that have been identfied because I'm not sure if they will affect what I need for my own projects.

**Comment by samber** [comment]
I just published a new GitHub project that would be similar to what is described here: https://github.com/samber/ro .

It supports generics, pipelining, subjects... After testing multiple ReactiveX libraries, I decided to stick with the RxJS API that seems the most mature to me.

After many implementation attempts, I removed channels for message passing. I consider it is not possible to fully respect the ReactiveX spec when the channel producer is released as soon as a consumer reads a message.

**Pull request closed without merging**
